/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meet_eat.server;

import org.junit.Test;
import static org.junit.Assert.*;

public class ApplicationTest {
    @Test
    public void testAppHasAGreeting() {
        Application classUnderTest = new Application();
        assertNotNull("application is uninitialized", classUnderTest);
    }
}
